# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: ClassicOldSong
    url: https://ccoooss.com
  - name: Frantic1048
    url: https://frantic1048.logdown.com/
  - name: Hclmaster
    url: https://hclmaster.github.io/
  - name: WANG Hs√º-Tung
    url: https://whst.github.io/

# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: Archives
    slug: archives
    url: /archives
  - name: Gallery
    slug: gallery
    url: https://photos.google.com/album/AF1QipNoqKYgspQo5O1YhlFXGCQ7p575KBH3Yxf8WHL4?hl=zh-CN
  - name: About
    slug: about
    url: /about

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/stkevintan
- slug: twitter
  url: https://twitter.com/kevinsfork
- slug: rss
	url: /atom.xml
